set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH PATH)

find_program(VCPKG_PREFERRED_PYTHON3 NAMES python3 python)
if(NOT VCPKG_PREFERRED_PYTHON3)
  message(FATAL_ERROR "Python was not found on PATH. Add your preferred Python 3 location to PATH before invoking vcpkg.")
endif()
set(PYTHON3 "${VCPKG_PREFERRED_PYTHON3}" CACHE FILEPATH "Python used by vcpkg Meson ports" FORCE)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_CMAKE_SYSTEM_VERSION 10)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

set(BIGOBJ_PORTS_LIST "grpc")
if(PORT IN_LIST BIGOBJ_PORTS_LIST)
  set(VCPKG_C_FLAGS "-Wa,-mbig-obj ")
  set(VCPKG_CXX_FLAGS "-Wa,-mbig-obj ")
endif()
