[string[]]$sections = @(
	"vcpkg help"
	"vcpkg help topics"
	"vcpkg help acquire"
	"vcpkg help acquire_project"
	"vcpkg help activate"
	"vcpkg help add"
	"vcpkg help assetcaching"
	"vcpkg help autocomplete"
	"vcpkg help binarycaching"

	"vcpkg help bootstrap-standalone"
	"vcpkg help build"
	"vcpkg help build-external"
	"vcpkg help ci"
	"vcpkg help commands"
	"vcpkg help contact"
	"vcpkg help create"
	"vcpkg help deactivate"
	"vcpkg help depend-info"
	"vcpkg help edit"
	"vcpkg help env"
	"vcpkg help export"
	"vcpkg help fetch"
	"vcpkg help find"
	"vcpkg help format-manifest"
	"vcpkg help generate-msbuild-props"
	"vcpkg help hash"
	"vcpkg help help"
	"vcpkg help install"
	"vcpkg help integrate"
	"vcpkg help list"
	"vcpkg help new"
	"vcpkg help owns"
	"vcpkg help portsdiff"
	"vcpkg help remove"
	"vcpkg help search"
	"vcpkg help triplet"
	"vcpkg help update"
	"vcpkg help upgrade"
	"vcpkg help use"
	"vcpkg help version"
	"vcpkg help versioning"
	"vcpkg help x-add-version"
	"vcpkg help x-check-support"
	"vcpkg help x-ci-clean"
	"vcpkg help x-ci-verify-versions"
	"vcpkg help x-download"
	"vcpkg help x-init-registry"
	"vcpkg help x-package-info"
	"vcpkg help x-regenerate"
	"vcpkg help x-set-installed"
	"vcpkg help x-update-baseline"
	"vcpkg help x-update-registry"
	"vcpkg help x-vsinstances"
	"vcpkg help z-applocal"
	"vcpkg help z-ce"
	"vcpkg help z-changelog"
	"vcpkg help z-extract"
	"vcpkg help z-generate-default-message-map"
	"vcpkg help z-preregister-telemetry"
	"vcpkg help z-print-config"
	"vcpkg help z-upload-metrics"
)

Write-Output "---"
Write-Output "lang: en"
Write-Output "subtitle: Automatically generated using the vcpkg help command."
Write-Output "title: vcpkg help"
Write-Output "..."
Write-Output ""

foreach ($section in $sections)
{
	Write-Output "## $section"
	Write-Output ""
	Write-Output "~~~~~~~"
	& Invoke-Expression "$section"
	Write-Output "~~~~~~~"
	Write-Output ""
}
