[string[]]$sections = @(
	"vcpkg.exe help"
	"vcpkg.exe help topics"
	"vcpkg.exe help acquire"
	"vcpkg.exe help acquire_project"
	"vcpkg.exe help activate"
	"vcpkg.exe help add"
	"vcpkg.exe help assetcaching"
	"vcpkg.exe help autocomplete"
	"vcpkg.exe help binarycaching"

	"vcpkg.exe help bootstrap-standalone"
	"vcpkg.exe help build"
	"vcpkg.exe help build-external"
	"vcpkg.exe help ci"
	"vcpkg.exe help commands"
	"vcpkg.exe help contact"
	"vcpkg.exe help create"
	"vcpkg.exe help deactivate"
	"vcpkg.exe help depend-info"
	"vcpkg.exe help edit"
	"vcpkg.exe help env"
	"vcpkg.exe help export"
	"vcpkg.exe help fetch"
	"vcpkg.exe help find"
	"vcpkg.exe help format-manifest"
	"vcpkg.exe help generate-msbuild-props"
	"vcpkg.exe help hash"
	"vcpkg.exe help help"
	"vcpkg.exe help install"
	"vcpkg.exe help integrate"
	"vcpkg.exe help list"
	"vcpkg.exe help new"
	"vcpkg.exe help owns"
	"vcpkg.exe help portsdiff"
	"vcpkg.exe help remove"
	"vcpkg.exe help search"
	"vcpkg.exe help triplet"
	"vcpkg.exe help update"
	"vcpkg.exe help upgrade"
	"vcpkg.exe help use"
	"vcpkg.exe help version"
	"vcpkg.exe help versioning"
	"vcpkg.exe help x-add-version"
	"vcpkg.exe help x-check-support"
	"vcpkg.exe help x-ci-clean"
	"vcpkg.exe help x-ci-verify-versions"
	"vcpkg.exe help x-download"
	"vcpkg.exe help x-init-registry"
	"vcpkg.exe help x-package-info"
	"vcpkg.exe help x-regenerate"
	"vcpkg.exe help x-set-installed"
	"vcpkg.exe help x-update-baseline"
	"vcpkg.exe help x-update-registry"
	"vcpkg.exe help x-vsinstances"
	"vcpkg.exe help z-applocal"
	"vcpkg.exe help z-ce"
	"vcpkg.exe help z-changelog"
	"vcpkg.exe help z-extract"
	"vcpkg.exe help z-generate-default-message-map"
	"vcpkg.exe help z-preregister-telemetry"
	"vcpkg.exe help z-print-config"
	"vcpkg.exe help z-upload-metrics"
)

Write-Output "---"
Write-Output "lang: en"
Write-Output "subtitle: Automatically generated using the vcpkg help command."
Write-Output "title: vcpkg help"
Write-Output "..."
Write-Output ""

foreach ($section in $sections)
{
	Write-Output "## $section"
	Write-Output ""
	Write-Output "~~~~~~~"
	& Invoke-Expression "$section"
	Write-Output "~~~~~~~"
	Write-Output ""
}
